name: release images

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y gcc-aarch64-linux-gnu qemu-user-static makeself

      - name: Make images
        run: ./make-images.sh

      - name: Release images
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Automatic Build"
          files: |
            output/*.img.xz
            output/*.run